-- Independent daily missions, keyed by the user's supplied local calendar date.
-- Legacy task/project/goal/note records remain untouched. Safe to re-run.
create table if not exists public.daily_checklist (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    title varchar(200) not null check (char_length(btrim(title)) > 0),
    date date not null,
    completed boolean not null default false,
    created_at timestamptz not null default now()
);
create index if not exists idx_daily_checklist_user_date on public.daily_checklist(user_id, date, id);

alter table public.daily_checklist enable row level security;
revoke all on table public.daily_checklist from public, anon, authenticated;
revoke all on sequence public.daily_checklist_id_seq from public, anon, authenticated;
drop policy if exists daily_checklist_owner_select on public.daily_checklist;
drop policy if exists daily_checklist_owner_insert on public.daily_checklist;
drop policy if exists daily_checklist_owner_update on public.daily_checklist;
drop policy if exists daily_checklist_owner_delete on public.daily_checklist;
create policy daily_checklist_owner_select on public.daily_checklist for select to authenticated using (user_id = (select auth.uid()));
create policy daily_checklist_owner_insert on public.daily_checklist for insert to authenticated with check (user_id = (select auth.uid()));
create policy daily_checklist_owner_update on public.daily_checklist for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy daily_checklist_owner_delete on public.daily_checklist for delete to authenticated using (user_id = (select auth.uid()));

create or replace function app_private.checklist_json(p_row public.daily_checklist)
returns jsonb language sql stable set search_path = '' as $$
    select pg_catalog.jsonb_build_object(
        'id', p_row.id, 'title', p_row.title, 'date', p_row.date,
        'completed', p_row.completed, 'createdAt', app_private.iso(p_row.created_at))
$$;

create or replace function public.api_checklist_create(p_title text, p_date date)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
    v_uid uuid := app_private.require_uid();
    v_row public.daily_checklist;
begin
    if p_date is null or p_title is null or pg_catalog.char_length(pg_catalog.btrim(p_title)) = 0
       or pg_catalog.char_length(p_title) > 200 then
        perform app_private.fail('VALIDATION_ERROR');
    end if;
    insert into public.daily_checklist(user_id, title, date, created_at)
    values (v_uid, pg_catalog.btrim(p_title), p_date, app_private.clock_now()) returning * into v_row;
    return app_private.checklist_json(v_row);
end
$$;

create or replace function public.api_checklist_list(p_date date)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare
    v_uid uuid := app_private.require_uid();
    v_items jsonb;
begin
    if p_date is null then perform app_private.fail('VALIDATION_ERROR'); end if;
    select coalesce(pg_catalog.jsonb_agg(app_private.checklist_json(c) order by c.id), '[]'::jsonb)
    into v_items from public.daily_checklist c where c.user_id = v_uid and c.date = p_date;
    return v_items;
end
$$;

create or replace function public.api_checklist_set_completed(p_id bigint, p_completed boolean)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
    v_uid uuid := app_private.require_uid();
    v_row public.daily_checklist;
begin
    if p_completed is null then perform app_private.fail('VALIDATION_ERROR'); end if;
    update public.daily_checklist set completed = p_completed
    where id = p_id and user_id = v_uid returning * into v_row;
    if not found then perform app_private.fail('CHECKLIST_NOT_FOUND'); end if;
    return app_private.checklist_json(v_row);
end
$$;

create or replace function public.api_checklist_delete(p_id bigint)
returns void language plpgsql security definer set search_path = '' as $$
declare
    v_uid uuid := app_private.require_uid();
begin
    delete from public.daily_checklist where id = p_id and user_id = v_uid;
    if not found then perform app_private.fail('CHECKLIST_NOT_FOUND'); end if;
end
$$;

create or replace function public.api_checklist_daily(p_from date, p_to date)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare
    v_uid uuid := app_private.require_uid();
    v_result jsonb;
begin
    if p_from is null or p_to is null or p_to < p_from then
        perform app_private.fail('ANALYTICS_INVALID_RANGE');
    end if;
    if p_to - p_from >= 366 then perform app_private.fail('ANALYTICS_RANGE_TOO_LARGE'); end if;
    select coalesce(pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object(
        'date', d.day::date, 'total', coalesce(t.total, 0), 'completed', coalesce(t.completed, 0)
    ) order by d.day), '[]'::jsonb) into v_result
    from pg_catalog.generate_series(p_from, p_to, '1 day'::interval) d(day)
    left join (
        select c.date, pg_catalog.count(*) as total,
               pg_catalog.count(*) filter (where c.completed) as completed
        from public.daily_checklist c
        where c.user_id = v_uid and c.date between p_from and p_to
        group by c.date
    ) t on t.date = d.day::date;
    return v_result;
end
$$;

select app_private.secure_api_functions();
