-- Focus Nagi schema for Supabase (PostgreSQL + Supabase Auth).
--
-- Translated from the former Flyway migrations V1..V8. Differences:
--   * every user-data table carries user_id -> auth.users(id); the legacy `owner`
--     table is replaced by Supabase Auth and is not recreated;
--   * references between user-data tables are composite (id, user_id) foreign keys,
--     so a row can never point at another user's project/task, even via direct REST calls;
--   * the "one RUNNING/PAUSED focus session" invariant is enforced per user;
--   * text length limits enforced by the API are also enforced by CHECK constraints.
--
-- Idempotent: safe to run more than once.

create schema if not exists app_private;
revoke all on schema app_private from public;

-- ---------------------------------------------------------------- project
create table if not exists public.project (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
    title varchar(120) not null,
    description text check (description is null or char_length(description) <= 2000),
    status varchar(20) not null default 'ACTIVE' check (status in ('ACTIVE', 'COMPLETED', 'ARCHIVED')),
    start_date date,
    due_date date,
    archived_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint project_dates_check check (due_date is null or start_date is null or due_date >= start_date),
    constraint project_id_user_key unique (id, user_id)
);

create index if not exists idx_project_user_status on public.project (user_id, status);
create index if not exists idx_project_user_created on public.project (user_id, created_at desc);

-- ---------------------------------------------------------------- task
create table if not exists public.task (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
    project_id bigint,
    title varchar(200) not null,
    description text check (description is null or char_length(description) <= 5000),
    status varchar(20) not null default 'TODO' check (status in ('TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    priority varchar(10) not null default 'MEDIUM' check (priority in ('LOW', 'MEDIUM', 'HIGH')),
    estimated_minutes int check (estimated_minutes is null or estimated_minutes between 1 and 10080),
    due_date date,
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint task_id_user_key unique (id, user_id),
    constraint task_project_fk foreign key (project_id, user_id) references public.project (id, user_id)
);

create index if not exists idx_task_user_status on public.task (user_id, status);
create index if not exists idx_task_project on public.task (project_id);
create index if not exists idx_task_user_due_date on public.task (user_id, due_date);
create index if not exists idx_task_user_completed_at on public.task (user_id, completed_at);
create index if not exists idx_task_user_created on public.task (user_id, created_at desc);

-- ---------------------------------------------------------------- subtask
create table if not exists public.subtask (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
    task_id bigint not null,
    title varchar(200) not null,
    completed boolean not null default false,
    created_at timestamptz not null default now(),
    constraint subtask_task_fk foreign key (task_id, user_id) references public.task (id, user_id) on delete cascade
);

create index if not exists idx_subtask_task on public.subtask (task_id);

-- ---------------------------------------------------------------- focus_session
create table if not exists public.focus_session (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
    task_id bigint,
    project_id bigint,
    started_at timestamptz not null,
    ended_at timestamptz,
    planned_focus_minutes int not null check (planned_focus_minutes between 1 and 1440),
    planned_break_minutes int check (planned_break_minutes is null or planned_break_minutes between 0 and 1440),
    paused_seconds_accum bigint not null default 0 check (paused_seconds_accum >= 0),
    last_paused_at timestamptz,
    actual_focus_seconds bigint check (actual_focus_seconds is null or actual_focus_seconds >= 0),
    status varchar(20) not null default 'RUNNING' check (status in ('RUNNING', 'PAUSED', 'COMPLETED', 'CANCELLED')),
    notes text check (notes is null or char_length(notes) <= 2000),
    created_at timestamptz not null default now(),
    version int not null default 0,
    constraint focus_session_pause_state_check check (status <> 'PAUSED' or last_paused_at is not null),
    constraint focus_session_task_fk foreign key (task_id, user_id) references public.task (id, user_id),
    constraint focus_session_project_fk foreign key (project_id, user_id) references public.project (id, user_id)
);

-- At most one RUNNING/PAUSED session per user, enforced by the database.
create unique index if not exists ux_focus_session_single_active
    on public.focus_session (user_id) where status in ('RUNNING', 'PAUSED');

create index if not exists idx_focus_session_user_started on public.focus_session (user_id, started_at);
create index if not exists idx_focus_session_user_status on public.focus_session (user_id, status);
create index if not exists idx_focus_session_task on public.focus_session (task_id);
create index if not exists idx_focus_session_project on public.focus_session (project_id);

-- ---------------------------------------------------------------- goal
create table if not exists public.goal (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
    title varchar(150) not null,
    description text check (description is null or char_length(description) <= 2000),
    type varchar(30) not null check (type in ('FOCUS_MINUTES', 'FOCUS_SESSIONS', 'TASKS_COMPLETED')),
    target_value int not null check (target_value > 0),
    period varchar(20) not null check (period in ('DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM')),
    start_date date not null,
    end_date date,
    status varchar(20) not null default 'ACTIVE' check (status in ('ACTIVE', 'COMPLETED', 'ARCHIVED')),
    project_id bigint,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint goal_dates_check check (end_date is null or end_date >= start_date),
    constraint goal_project_fk foreign key (project_id, user_id) references public.project (id, user_id)
);

create index if not exists idx_goal_user_status on public.goal (user_id, status);
create index if not exists idx_goal_project on public.goal (project_id);

-- ---------------------------------------------------------------- note
create table if not exists public.note (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
    title varchar(150) not null,
    content text check (content is null or char_length(content) <= 20000),
    pinned boolean not null default false,
    project_id bigint,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint note_project_fk foreign key (project_id, user_id) references public.project (id, user_id)
);

create index if not exists idx_note_user_pinned_updated on public.note (user_id, pinned desc, updated_at desc);
create index if not exists idx_note_project on public.note (project_id);

-- ---------------------------------------------------------------- journal_entry
create table if not exists public.journal_entry (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
    entry_date date not null,
    content text not null check (char_length(content) <= 50000),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_journal_entry_user_date on public.journal_entry (user_id, entry_date);
